import type { DadosFicha } from './schema';

/** Rótulos como aparecem no PDF da ficha, na mesma ordem. */
export const ROTULOS_FICHA: Record<keyof DadosFicha, string> = {
  nomeCompleto: 'Nome completo',
  nascimento: 'Nascimento',
  cpf: 'CPF',
  rg: 'RG',
  passaporte: 'Passaporte',
  vencimentoPassaporte: 'Vencimento do passaporte',
  nacionalidade: 'Nacionalidade',
  cep: 'CEP',
  endereco: 'Endereço',
  numeroComplemento: 'Número/complemento',
  bairro: 'Bairro',
  cidade: 'Cidade',
  estado: 'Estado',
  pais: 'País',
  celular: 'Celular',
  email: 'E-mail',
  profissao: 'Profissão',
  estadoCivil: 'Estado civil',
  contatoEmergencia: 'Contato de emergência',
  telefoneEmergencia: 'Telefone emergência',
  medicamentoRegular: 'Medicamento regular',
  alergias: 'Alergias',
  tipoSanguineo: 'Tipo sanguíneo',
  convenioMedico: 'Convênio médico',
  antecedentesClinicos: 'Antecedentes clínicos',
  condicionamentoFisico: 'Condicionamento físico',
  sabeNadar: 'Sabe nadar?',
  diabetico: 'Diabético(a)?',
  disturbioCardioRespiratorio: 'Distúrbio cardio-respiratório?',
  restricoesAlimentares: 'Restrições alimentares',
  descricaoRestricoes: 'Descrição das restrições alimentares',
  vacinaTetano: 'Vacinado(a) contra tétano',
  vacinaFebreAmarela: 'Vacinado(a) contra febre amarela',
  vacinaCovid: 'Vacinado(a) contra Covid',
  outrasObservacoes: 'Outras observações',
};
